version: '3'
services:
  backend:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama

  frontend:
    build: .
    ports:
      - "5173:80"
    depends_on:
      - backend

  ollama:
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

volumes:
  ollama_data:
